### PR TITLE
Better column widths with single-line texts

### PR DESCRIPTION
**Pull request by tsujan**
Fixes https://github.com/lxqt/lxqt/issues/1688

### CODE REVIEW

**Comment by stefonarch** [comment]
Hm I compiled branch column_widths but it does not remember any width here...

**Comment by tsujan** [comment]
> but it does not remember any width here

It isn't supposed to. Column widths are determined by their longest texts, as before. This is only for removing multiple-lines + giving the last column an appropriate width.

**Comment by stefonarch** [comment]
Ok, scrolling down there are those XF86MonBrightnessDown and audio things which are much larger than most of the others. My point is that's still   unusable when freshly opened.
https://user-images.githubusercontent.com/10681413/54077597-fac3d880-42ba-11e9-9632-3915219c0c3c.png

But that is already discussed [here](https://github.com/lxqt/lxqt/issues/1691)

**Comment by tsujan** [comment]
> My point is that's still unusable when freshly opened.

Why?! There are long texts inside those columns and you'll see them if you scroll down. "Unusable" because you should scroll?!

Please also note the subject of this PR and what it's supposed to fix!

**Comment by stefonarch** [comment]
I meant unusable because you see only 3 columns and something and you have first to increment first window size to see all. The wrap issue is fixed.

**Comment by tsujan** [comment]
> because you see only 3 columns...

The user could resize the window (if he/she doesn't want to use the horizontal scrollbar for whatever reason) and the size will be remembered; but not in this PR -- I'm making another PR for that ;)

**Comment by tsujan** [comment]
The above-mentioned PR is made here: https://github.com/lxqt/lxqt-globalkeys/pull/115

Together with the current PR, they solve practical problems.

IMHO, saving column widths of a config dialog is a bit of an overkill because a config dialog isn't opened so frequently. However, it *is* possible.

**Pull request merged**
