### PR TITLE
Standard desktop file

### PR DESCRIPTION
**Pull request by stefonarch**
Related https://github.com/lxqt/lxqt-config/pull/1015

Adding (X11) ?
`Desktop Entry/Comment: "Configure global shortcut keys (X11)"`

### CODE REVIEW

**Comment by tsujan** [comment]
Adding "global" is good (for not mistaking them for shortcuts of apps), but perhaps "in LXQt" should be preserved.

Don't you fear invalidating translations?

**Comment by stefonarch** [comment]
I think `LXQt` could be removed everwyhere as they are 
1. shown only under LXQt 
2. and both in panel menus and in Configuration Center are placed under "LXQt Settings". No redundant things, you know ;)

I don't exactly remember what happens with translations, I think they get marked as "Needs editing" but I'm not sure if they are still shown or not. But anyway, also translations needs updating, but translators don't get notifications automatically as they do for new strings.

**Comment by tsujan** [comment]
For example, in Fancy Menu, "in LXQt" is the only clue to its relation to LXQt.

There's no need to be worried about a few extra words here, because `Comment` is shown in a tooltip if it's shown at all, and tooltips aren't elided.

**Comment by stefonarch** [comment]
>For example, in Fancy Menu, "in LXQt" is the only clue to its relation to LXQt.

That's true if  `lxqt-applications-menu` is used, I'm using "compact", don't remember the ups and downs.

immagine

But with that argument we would need to add _LXQt_ everywhere while I removed it in https://github.com/lxqt/lxqt-config/pull/1015 for _Appearance_ and _Locale_ too.

**Comment by tsujan** [comment]
> But with that argument we would need to add LXQt everywhere

I don't know, but if we do it, it shouldn't be in `Name`.

**Comment by stefonarch** [comment]
> > But with that argument we would need to add LXQt everywhere
> 
> I don't know, but if we do it, it shouldn't be in `Name`.

As I said I'm for _removing_ it where it is now, as it's self-explanatory as only shown in LXQt.

**Comment by tsujan** [comment]
I have no strong opinion in that regard. As far as I am concerned, you could do it as you see fit; I might just review your changes.

**Comment by stefonarch** [comment]
From my point of view this and https://github.com/lxqt/lxqt-config/pull/1015 are ready.

**Review by tsujan — APPROVED** [review]
GTM

**Comment by stefonarch** [comment]
In weblate the translations are only marked as "Needs editing" but are still compiled, not switched back to english, so existing translations are conserved.

immagine

**Pull request merged**
