### PR TITLE
Prerelease changes

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by tsujan** [comment]
@stefonarch 
The release note will be:

The asynchronous behavior of Xlib is kept intact. It guarantees that the global shortcut daemon starts correctly with the session after a change in the behavior of `libx11` 1.7.3.1.

**Comment by stefonarch** [comment]
I managed to get jekyll working on arch again, tell me the date and I'll prepare a PR, I've a draft ready.

**Comment by tsujan** [comment]
> tell me the date and I'll prepare a PR, I've a draft ready.

I've set it to 2022-01-07, for more tests, but it could be changed if you prefer another date.

**Comment by stefonarch** [comment]
Ok better waiting some days.
https://github.com/lxqt/lxqt.github.io/pull/90

**Comment by tsujan** [comment]
Good. Will merge both.

**Pull request merged**
