### PR TITLE
WIP: move shortcuts config fom /etc/xdg/lxqt to /usr/share/lxqt

### PR DESCRIPTION
**Pull request by agaida**
same as for session: make it easy for distributions to provide own configurations

### CODE REVIEW

**Comment by tsimonq2** [comment]
👍

**Comment by agaida** [comment]
cool, hard coded ...

**Comment by wxl** [comment]
I just stumbled across this one as I can see that globalkeys doesn't respect XDG variables, which is really problematic. That said, I'm not sure I quite understand what the problem is @palinek. Are you simply saying we need to provide handling for `configFiles` so that if no specific file is passed on the command line, then the config is grabbed from the XDG variables (which is not yet done), finally falling through to `DEFAULT_CONFIG` (as is currently done)?

**Comment by palinek** [comment]
> I'm not sure I quite understand what the problem 

The problem is the mess in the daemon code. Here the self-implementation of config files search hierarchy.

**Comment by wxl** [comment]
I guess what I'm asking is what can we do to fix it?

**Comment by palinek** [comment]
> I guess what I'm asking is what can we do to fix it?

Now "just" review & test #123

**Pull request merged**
