### PR TITLE
Update shortcut descriptions in globalkeyshortcuts.conf

### PR DESCRIPTION
**Pull request by isf63**
Updates the descriptions in `/usr/share/lxqt/globalkeyshortcuts.conf` for default shortcuts, which are displayed in Global Actions Manager.

- Made several generic
- Fixed capitalization

### CODE REVIEW

**Comment by isf63** [comment]
Because these same entries can appear in `.config/lxqt/globalkeyshortcuts.conf`, existing install users must hit 'Default' to get the updated descriptions. That resets custom keybinds which is undesirable, but thankfully hitting 'Default' is only required for getting the updated descriptions from `/usr/share/lxqt/globalkeyshortcuts.conf`, and not doing so, nothing changes and there are no duplicates.

@stefonarch, Do you think this is a worthwhile change?

**Comment by stefonarch** [comment]
Generic as for browser is ok, but if the app `is` qterminal the description should be "QTerminal" as it is, same for pcmanfm(-qt).  

So if any I'd change only 
* Lock screen (with space)
* Monitor settings
* Screenshot

In any case changing user settings is a no-go.

**Comment by tsujan** [comment]
> In any case changing user settings is a no-go.

Right. LXQt doesn't do that.

**Comment by isf63** [comment]
I agree with not changing user settings, I mentioned the user/system settings distinction because I didn't want anything conflicting. Thankfully there are no duplicates in any case and new installations (and when Reset) can get the corrected names.

**Pull request closed without merging**
