### PR TITLE
daemon: Use XDG hierarchy if no config file given on command line

### PR DESCRIPTION
**Pull request by palinek**
@wxl, @agaida  Please, test this thoroughly ...

### CODE REVIEW

**Comment by wxl** [comment]
Ok, I was struggling with this earlier, but I realized the issue is I was running my system version rather than the one I compiled :man_facepalming: 

So here's what I did:
 1. `kill`ed the running `lxqt-globalkeysd` process
 1. Moved and renamed all the config files (I had one in `$HOME/.config/lxqt` and one in `/etc/xdg/lxqt`) to my `$HOME` so they'd be ignored
 1. Copied one of the config files to `/etc/xdg/xdg-Lubuntu/lxqt` as `/etc/xdg/xdg-Lubuntu` is the first in our `$XDG_CONFIG_DIRS`
 1. Edited that file so that one of my definitions was unenabled, making it unique relative to any other configuration
 1. Ran the freshly compiled `lxqt-globalkeysd`
 1. Checked in the GUI and the respective definition was unenabled
 1. Checked the new config file created in `$HOME/.config/lxqt` and the respective definition was unenabled

Works for me!

@tsimonq2 want to give it a go?

**Comment by monetaryabyss** [comment]
On a fresh installation of Lubuntu in a virtual machine using the same method as @wxl I was also able to have success. The globalkeys config file was pulled from my XDG defined directory when there were no other config files.

**Comment by tsimonq2** [comment]
Hi, I'm curious why this was merged into the `xdg-config` branch instead of `master`.

What is stopping the merge?

Thanks.

**Comment by palinek** [comment]
Because it should be part of the #60. Now I believe #60 can be merged.

**Pull request merged**
